### ISSUE TITLE
[Feature] User Data section: enable uploading CSVs

### ISSUE THREAD

**Issue by gty3310** [LexiconSpark/data-analysis-copilot#1]
### Description
This multi-tab interface is designed to streamline the process of uploading, viewing, and managing different types of data. It provides a user-friendly way to handle multiple datasets within a single platform, making it ideal for applications in research, monitoring, and data analysis.

![CleanShot 2024-06-25 at 22 12 04@2x](https://github.com/LexiconSpark/data-analysis-copilot/assets/6131820/5d6f20f3-7132-47c1-900c-2ca767c3f4e8)

### Requirements
- [ ] have a starting screen with 'upload data' and 'use sample data' button
- [ ] build a multi tab interface that allow people to upload different types of data, with a ‘+’ button for adding a uploading piece of data. each tab's name is the file name of the table uploaded
- [ ] within the code, change st.session_state.df to st.session_state.user_data which is a dictionary where the key will be the file name and the body will be the file content read as dataframe

### Implementation Plan
See Requirements

### Additional Notes
- follow this for inspirations: https://www.perplexity.ai/search/describe-this-multi-V9.Xm0r0RwGPB4.oAPv.EA
